server:
  port: 8001

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/api/products/**
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/orders/**

management:
  endpoints:
    web:
      exposure:
        include: info, health

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/